Bug 858402: reading a file which is not being used for any other reason to avoid Windows read error
WindowsError: [Error 13] The process cannot access the file because it is being used by another process